Bug #2066276: ipv6 test failures: AttributeError: 'RRHeader' object has no attribute '_address'
fix: parse DNS results correctly

(cherry picked from commit 4f6ef7d4e2feab5445b39330949ed5a13d10d526)
(cherry picked from commit 557d3f62aa3399150b84cfc95949cd3416c6ce04)

Limit test processes in parallel to 4 by default.

It's possible to change the number of parallel processes by passing
in the MAAS_MAX_TEST_PROCESSES environment variable. For example:
MAAS_MAX_TEST_PROCESSES=8 utilities/run-py-tests-ci

This aims to reduce the number of intermittent failures in our CI.

(cherry picked from commit b2df4b603143d36e95b7e0d8e6b442fd2ac7c8ed)

Apply intermittent test failure fix from e4d49a5503.